"""Portfolio Foundation: exactly 11 domain tables. Frozen initial revision."""

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001_portfolio_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_status_allowed"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_table(
        "instrument",
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mic", sa.Text(), nullable=False),
        sa.Column("asset_type", sa.Text(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("market_timezone", sa.Text(), nullable=False),
        sa.Column("isin", sa.Text(), nullable=True),
        sa.Column("cik", sa.Text(), nullable=True),
        sa.Column("dart_corp_code", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("asset_type IN ('EQUITY', 'ETF')", name="ck_asset_type_allowed"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
    )
    op.create_index(op.f("ix_instrument_cik"), "instrument", ["cik"], unique=False)
    op.create_index(
        op.f("ix_instrument_dart_corp_code"), "instrument", ["dart_corp_code"], unique=False
    )
    op.create_index("ix_instrument_symbol_mic", "instrument", ["symbol", "mic"], unique=False)
    op.create_table(
        "broker_account",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.Text(), nullable=False),
        sa.Column("account_key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("masked_account", sa.Text(), nullable=True),
        sa.Column("credential_ref", sa.Text(), nullable=True),
        sa.Column("external_account_ref_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("source_mode", sa.Text(), nullable=False),
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("broker IN ('KIS', 'TOSS', 'MANUAL')", name="ck_broker_allowed"),
        sa.CheckConstraint(
            "source_mode IN ('BROKER_API', 'MANUAL')", name="ck_source_mode_allowed"
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'DEGRADED', 'DISABLED', 'PENDING')", name="ck_status_allowed"
        ),
        sa.CheckConstraint("version >= 1", name="ck_account_version"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_broker_account_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_account")),
        sa.UniqueConstraint(
            "user_id", "broker", "account_key", name=op.f("uq_broker_account_user_id")
        ),
    )
    op.create_table(
        "broker_instrument_map",
        sa.Column("broker", sa.Text(), nullable=False),
        sa.Column("external_symbol", sa.Text(), nullable=False),
        sa.Column("external_market", sa.Text(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mapping_source", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("broker"), "="),
            (sa.column("external_symbol"), "="),
            (sa.column("external_market"), "="),
            (sa.text("tstzrange(valid_from, valid_to, '[)')"), "&&"),
            using="gist",
            name="ex_map_period",
        ),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from", name="ck_map_period"),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_broker_instrument_map_instrument_id_instrument"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_instrument_map")),
        sa.UniqueConstraint(
            "broker",
            "external_symbol",
            "external_market",
            "valid_from",
            name=op.f("uq_broker_instrument_map_broker"),
        ),
    )
    op.create_index(
        op.f("ix_broker_instrument_map_instrument_id"),
        "broker_instrument_map",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        "uq_map_current",
        "broker_instrument_map",
        ["broker", "external_symbol", "external_market"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "idempotency_request",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="IN_PROGRESS", nullable=False),
        sa.Column("response_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("resource_type", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'COMPLETED' OR (response_status BETWEEN 200 AND 299 AND response_status IS NOT NULL AND response_body IS NOT NULL AND resource_type IS NOT NULL AND resource_id IS NOT NULL AND completed_at IS NOT NULL)",
            name="ck_idempotency_completed",
        ),
        sa.CheckConstraint("status IN ('IN_PROGRESS', 'COMPLETED')", name="ck_status_allowed"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_idempotency_request_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_request")),
        sa.UniqueConstraint(
            "user_id", "operation", "idempotency_key", name=op.f("uq_idempotency_request_user_id")
        ),
    )
    op.create_index(
        "ix_idempotency_resource",
        "idempotency_request",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "outbox_message",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_key", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("aggregate_type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CLAIMED' OR (lease_token IS NOT NULL AND lease_until IS NOT NULL)",
            name="ck_outbox_claim",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'CLAIMED', 'PUBLISHED', 'DONE', 'DEFERRED', 'DEAD')",
            name="ck_status_allowed",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_outbox_attempt"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_outbox_message_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_message")),
        sa.UniqueConstraint("event_key", name=op.f("uq_outbox_message_event_key")),
    )
    op.create_index(
        "ix_outbox_aggregate", "outbox_message", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_message_lease_until"), "outbox_message", ["lease_until"], unique=False
    )
    op.create_index(op.f("ix_outbox_message_user_id"), "outbox_message", ["user_id"], unique=False)
    op.create_index("ix_outbox_pending", "outbox_message", ["status", "available_at"], unique=False)
    op.create_table(
        "position_adjustment",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("quantity_mode", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("boundary_basis", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("entry_key", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'OPENING_BALANCE' AND quantity_mode = 'ABSOLUTE' AND quantity >= 0) OR (kind IN ('TRANSFER', 'SPLIT_CORRECTION', 'OTHER') AND quantity_mode = 'DELTA' AND quantity <> 0)",
            name="ck_adjustment_quantity_mode",
        ),
        sa.CheckConstraint(
            "boundary_basis IN ('TRADE_TIME', 'SETTLED', 'MANUAL')",
            name="ck_boundary_basis_allowed",
        ),
        sa.CheckConstraint(
            "state <> 'VOID' OR (void_reason IS NOT NULL AND length(trim(void_reason)) > 0)",
            name="ck_adjustment_void_reason",
        ),
        sa.CheckConstraint("state IN ('ACTIVE', 'VOID')", name="ck_state_allowed"),
        sa.CheckConstraint("unit_cost IS NULL OR unit_cost >= 0", name="ck_adjustment_cost"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_account.id"],
            name=op.f("fk_position_adjustment_account_id_broker_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_position_adjustment_instrument_id_instrument"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_adjustment")),
        sa.UniqueConstraint(
            "account_id", "entry_key", name=op.f("uq_position_adjustment_account_id")
        ),
    )
    op.create_index(
        "ix_adjustment_effective",
        "position_adjustment",
        ["account_id", "instrument_id", sa.literal_column("effective_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_adjustment_instrument_id"),
        "position_adjustment",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        "uq_adjustment_opening",
        "position_adjustment",
        ["account_id", "instrument_id", "effective_at"],
        unique=True,
        postgresql_where=sa.text("state = 'ACTIVE' AND kind = 'OPENING_BALANCE'"),
    )
    op.create_table(
        "sync_run",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="QUEUED", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "coverage",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("snapshot", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')",
            name="ck_status_allowed",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_sync_attempt"),
        sa.CheckConstraint("finished_at >= started_at", name="ck_sync_finish"),
        sa.CheckConstraint("window_to >= window_from", name="ck_sync_window"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_account.id"],
            name=op.f("fk_sync_run_account_id_broker_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
        sa.UniqueConstraint("request_key", name=op.f("uq_sync_run_request_key")),
    )
    op.create_index(
        "ix_sync_account_scope_created",
        "sync_run",
        ["account_id", "scope", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_sync_pending",
        "sync_run",
        ["status", "lease_until"],
        unique=False,
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "account_position",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("avg_cost", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("quantity_basis", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of_basis", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("quality", sa.Text(), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("as_of_basis IN ('BROKER', 'OBSERVED')", name="ck_as_of_basis_allowed"),
        sa.CheckConstraint("quality IN ('GOOD', 'STALE', 'UNKNOWN')", name="ck_quality_allowed"),
        sa.CheckConstraint(
            "quantity_basis IN ('TRADE_TIME', 'SETTLED', 'UNKNOWN')",
            name="ck_quantity_basis_allowed",
        ),
        sa.CheckConstraint("source IN ('BROKER_API', 'MANUAL')", name="ck_source_allowed"),
        sa.CheckConstraint(
            "quantity >= 0 AND (available_quantity IS NULL OR available_quantity >= 0) AND (avg_cost IS NULL OR avg_cost >= 0)",
            name="ck_position_amounts",
        ),
        sa.CheckConstraint("version >= 1", name="ck_position_version"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_account.id"],
            name=op.f("fk_account_position_account_id_broker_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_account_position_instrument_id_instrument"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_run.id"],
            name=op.f("fk_account_position_sync_run_id_sync_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_position")),
        sa.UniqueConstraint(
            "account_id", "scope", "instrument_id", name=op.f("uq_account_position_account_id")
        ),
    )
    op.create_index(
        op.f("ix_account_position_instrument_id"),
        "account_position",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_position_sync_run_id"), "account_position", ["sync_run_id"], unique=False
    )
    op.create_table(
        "reconciliation_result",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("calculated_quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("broker_quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("difference", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column(
            "tolerance", sa.Numeric(precision=28, scale=10), server_default="0", nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.Text(), nullable=False),
        sa.Column(
            "basis",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(calculated_quantity IS NULL AND difference IS NULL AND status = 'INDETERMINATE') OR (calculated_quantity IS NOT NULL AND difference IS NOT NULL AND difference = broker_quantity - calculated_quantity)",
            name="ck_reconciliation_difference",
        ),
        sa.CheckConstraint(
            "status = 'INDETERMINATE' OR (status = 'MATCH' AND abs(difference) <= tolerance) OR (status = 'MISMATCH' AND abs(difference) > tolerance)",
            name="ck_reconciliation_status",
        ),
        sa.CheckConstraint(
            "status IN ('MATCH', 'MISMATCH', 'INDETERMINATE')", name="ck_status_allowed"
        ),
        sa.CheckConstraint(
            "broker_quantity >= 0 AND tolerance >= 0", name="ck_reconciliation_amounts"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_account.id"],
            name=op.f("fk_reconciliation_result_account_id_broker_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_reconciliation_result_instrument_id_instrument"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_run.id"],
            name=op.f("fk_reconciliation_result_sync_run_id_sync_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_result")),
        sa.UniqueConstraint(
            "sync_run_id",
            "scope",
            "instrument_id",
            name=op.f("uq_reconciliation_result_sync_run_id"),
        ),
    )
    op.create_index(
        "ix_reconciliation_account_status_created",
        "reconciliation_result",
        ["account_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_result_instrument_id"),
        "reconciliation_result",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "trade_execution",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("granularity", sa.Text(), nullable=False),
        sa.Column("identity_key", sa.Text(), nullable=False),
        sa.Column("external_execution_id", sa.Text(), nullable=True),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("tax", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("source_timezone", sa.Text(), nullable=False),
        sa.Column("time_precision", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "granularity IN ('FILL', 'ORDER_AGGREGATE')", name="ck_granularity_allowed"
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name="ck_side_allowed"),
        sa.CheckConstraint("source IN ('BROKER_API', 'MANUAL')", name="ck_source_allowed"),
        sa.CheckConstraint("state IN ('ACTIVE', 'VOID')", name="ck_state_allowed"),
        sa.CheckConstraint(
            "time_precision IN ('SECOND', 'MILLISECOND', 'DAY', 'UNKNOWN')",
            name="ck_time_precision_allowed",
        ),
        sa.CheckConstraint(
            "quantity > 0 AND price >= 0 AND (fee IS NULL OR fee >= 0) AND (tax IS NULL OR tax >= 0) AND revision >= 1",
            name="ck_trade_amounts",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["broker_account.id"],
            name=op.f("fk_trade_execution_account_id_broker_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_trade_execution_instrument_id_instrument"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_run.id"],
            name=op.f("fk_trade_execution_sync_run_id_sync_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_execution")),
        sa.UniqueConstraint(
            "account_id", "identity_key", name=op.f("uq_trade_execution_account_id")
        ),
    )
    op.create_index(
        "ix_trade_account_instrument_date",
        "trade_execution",
        ["account_id", "instrument_id", "trade_date", "executed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_execution_instrument_id"), "trade_execution", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_execution_sync_run_id"), "trade_execution", ["sync_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("trade_execution")
    op.drop_table("reconciliation_result")
    op.drop_table("account_position")
    op.drop_table("sync_run")
    op.drop_table("position_adjustment")
    op.drop_table("outbox_message")
    op.drop_table("idempotency_request")
    op.drop_table("broker_instrument_map")
    op.drop_table("broker_account")
    op.drop_table("instrument")
    op.drop_table("app_user")
